site_name: NaviSense
repo_url: https://github.com/sceptysm/NaviSense-2025-2026
repo_name: NaviSense 2025-2026

theme:
  name: readthedocs
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - content.code.copy

# Defines the structure of the documentation
nav:
  - Home: index.md
  - Way of Working: way-of-working.md
  - Architecture:
      - Decisions: architecture/design-decisions.md

# - Section name: 
#    - Page name: path/to/page.md

markdown_extensions:
  - pymdownx.arithmatex # latex 
  - admonition
  - footnotes
  - toc:
      permalink: true
